### ISSUE TITLE
PDF proxy doesn't work in prod

### ISSUE THREAD

**Issue by Kelbie** [Kelbie/student-log#18]

**Comment by Kelbie** [comment]
``` 
 Error: Error: Unable to run pdflatex command.
      at ChildProcess.<anonymous> (/home/kevin/resumake.io/app/server/node_modules/node-latex/index.js:146:22)
      at ChildProcess.emit (events.js:321:20)
      at ChildProcess.EventEmitter.emit (domain.js:485:12)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
      at onErrorNT (internal/child_process.js:467:16)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)


  Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
      at Socket.Writable.write (_stream_writable.js:322:17)
      at StringStream.ondata (/home/kevin/resumake.io/app/server/node_modules/readable-stream/lib/_stream_readable.js:612:20)
      at StringStream.emit (events.js:321:20)
      at StringStream.EventEmitter.emit (domain.js:485:12)
      at addChunk (/home/kevin/resumake.io/app/server/node_modules/readable-stream/lib/_stream_readable.js:284:12)
      at readableAddChunk (/home/kevin/resumake.io/app/server/node_modules/readable-stream/lib/_stream_readable.js:271:11)
      at StringStream.Readable.push (/home/kevin/resumake.io/app/server/node_modules/readable-stream/lib/_stream_readable.js:238:10)
      at /home/kevin/resumake.io/app/server/node_modules/string-to-stream/index.js:18:12
      at processTicksAndRejections (internal/process/task_queues.js:79:11)```

**Comment by Kelbie** [comment]
fixed by installing xetex: https://tex.stackexchange.com/a/179811
